# Site settings
title: elderec.org

description: > # this means to ignore newlines until "baseurl:"
  random technical musings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://elderec.org" # the base hostname & protocol for your site
permalink: /:year/:month/:title

twitter_username: elderec
github_username:  elderec

# highlighter settings
highlighter: rouge

# pagination settings
pagination:
  enabled: true

# Build settings
markdown: kramdown

# gems to include
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate-v2
